apiVersion: apps/v1
kind: Deployment
metadata:
  name: kaiburr-task-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kaiburr-task-app
  template:
    metadata:
      labels:
        app: kaiburr-task-app
    spec:
      serviceAccountName: task-app-sa
      containers:
      - name: kaiburr-task-app
        image: apnpro/kaiburr-task-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATA_MONGODB_URI
          value: "mongodb://root:hkGk3d4mz2@my-mongo-mongodb:27017/kaiburr_tasks?authSource=admin"
